on:
  push:
    branches: [ "master" ]


jobs:
  apply-migrations:
    environment: manual-deploy
    runs-on: ubuntu-latest
    container: node:22-alpine

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Apply Prisma migrations
        run: npm run prisma:deploy

  deploy:
    runs-on: ubuntu-latest
    needs: apply-migrations
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get package version
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Deploy on Render
        env:
          hook_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          docker_url: docker.io/luskas8/agro-hub:${{ steps.get_version.outputs.VERSION }}
        run: curl "$hook_url&imgURL=$docker_url"